#!/usr/bin/env python2

import sys, os, string
import urllib
from subprocess import Popen,PIPE,STDOUT
from zpbuild_globals_ng import builddefs, zprepo, zptemp, zpkeep
import codecs, json, shutil, pkg_resources

if not os.path.exists(builddefs):
	print("Cannot find build definition %s." % builddefs)
	sys.exit(1)

def readBuildDefs(json_fn=builddefs):
	l = codecs.open(json_fn, 'r', 'utf-8')
	my_json = json.load(l)
	l.close()
	return my_json

build_count = 0
build_fail = 0
build_exist = 0

if os.path.exists(zpkeep):
	shutil.rmtree(zpkeep)
logdir=os.path.join(zprepo,"log")
logdir_succ = logdir + "_succ"
logdir_fail = logdir + "_fail"
for ld in ( logdir, logdir_succ, logdir_fail ):
	if not os.path.isdir(ld):
		os.makedirs(ld)
	for f in os.listdir(ld):
		os.unlink(os.path.join(ld,f))

def log(msg):
	sys.stdout.write(msg+"\n")
	#blog.write(msg)

def buildPack(zpname, zenpack_json, rel_version):
	global build_count, build_fail, build_exist
	# environment variables passed to build script:
	pyname = zenpack_json["Python name"]
	build_env = { 
		"PATH" : os.environ["PATH"],
		"ZPTEMP" : zptemp, 
		"ZPREPO" : zprepo, 
		"PKGDIR" : zprepo + "/zenpacks/" + pyname + "/" + rel_version,
		"KEEPDIR" : zpkeep + "/" + pyname + "-" + rel_version,
		"TMPDIR" : zptemp + "/build/" + pyname + "/" + rel_version,
		"CLONECACHE" : zptemp + "/cloned-repositories/" + pyname,
		"BASE_OUTFILE" : pyname+"-"+rel_version+".egg",
		"PYTHON_VERSION" : python_version,
		"ZENPACK_PY_NAME" : pyname,
		"TITLE": zpname, 
		"VERSION" : rel_version, 
		"TAG": zenpack_json["Releases"][rel_version]["Tag"], 
		"SRC_URI" : zenpack_json["Source URI"]
	}
	build_env["OUTFILE"] = build_env["PKGDIR"] + "/" + build_env["BASE_OUTFILE"]
	pipe = Popen(os.getcwd() + "/build.sh", env=build_env, stderr=STDOUT, stdout=PIPE)
	output = pipe.communicate()[0]
	status = pipe.wait()
	logfn = "{0[ZENPACK_PY_NAME]}-{0[VERSION]}.txt".format(build_env)
	if os.path.exists(os.path.join(logdir,logfn)):
		log("\nError: Log for %s already exists -- indicates duplicate build entry or wrong/duplicate ZenPack name\n" % logfn)
		return
	a = open(os.path.join(logdir,logfn),'w')
	if status == 0:
		os.symlink("../log/" + logfn, os.path.join(logdir_succ,logfn))
		log(": build OK\n")
	elif status == 2:
		build_fail += 1
		os.symlink("../log/" + logfn, os.path.join(logdir_fail,logfn))
		log(": build FAILED\n")
	elif status == 1:
		os.symlink("../log/" + logfn, os.path.join(logdir_succ,logfn))
		build_exist += 1
		log(": skipped\n")
	a.write(output)
	a.close()
	# grab deps from egg, add them to our python-ized JSON to be output later:
	zenpack_json["Releases"][rel_version]["Requires"] = []
	if os.path.exists(build_env["KEEPDIR"] + "/requires.txt"):
		log("Parsing dependencies for %s-%s..." % ( zpname, rel_version )) 
		r = open(build_env["KEEPDIR"] + "/requires.txt", 'r')
		# parse setuptools version strings and convert to a good format for the wiki, and humanity:
		# { "ZenPack" : "ZenPacks.zenoss.foo", "Version" : [ ">= 1.0", "<= 3.0" ]
		deps = []
		for x in pkg_resources.parse_requirements(r.readlines()):
			d = { "ZenPack" : x.project_name }
			v = []
			for y in x.specs:
				v.append(" ".join(y))
			if v != []:
				d["Version"] = v
			deps.append(d)
		zenpack_json["Releases"][rel_version]["Requires"] = deps
		r.close()
	# write out JSON that can be imported by the wiki - this is JSON for this release only.
	jsonfile = build_env["PKGDIR"] + "/release.json"
	log("Writing out JSON to %s..." % jsonfile )
	a = open(jsonfile, 'w')
	json.dump(zenpack_json["Releases"][rel_version], a, sort_keys=True, indent=4, separators=(',',": "))
	a.close()
	build_count += 1

zenpacks = readBuildDefs()
python_version="2.7"
for zp_name in zenpacks:
	# get python name from name of repo:
	pyname = zenpacks[zp_name]["Source URI"]
	if pyname == None:
		log("ZenPack %s has no Source URI, skipping..." % zp_name)
		continue
	print zenpacks[zp_name]
	if pyname[-4:] == ".git":
		pyname = pyname[:-4]
	pyname = pyname.split("/")[-1]
	zenpacks[zp_name]["Python name"] = pyname
	# remove namespace prefix from real-world ZenPack name:
	zenpacks[zp_name]["Name"] = ":".join(zp_name.split(":")[1:])
	if not "Releases" in zenpacks[zp_name]:
		log("No releases for %s" % zp_name)
		continue
	for rel_version in zenpacks[zp_name]["Releases"]:
		rel_info = zenpacks[zp_name]["Releases"][rel_version]
		if "ZenPack" in rel_info:
			# delete redundant info in JSON, no need to repeat ourselves:
			del rel_info["ZenPack"]
		if "Version" in rel_info:
			# delete redundant info in JSON, no need to repeat ourselves. Want clean output.
			del rel_info["Version"]
		log("Processing %s version %s (building with python %s)..." % ( zp_name, rel_version, python_version ))
		buildPack(zp_name, zenpacks[zp_name], rel_version)
	# now write out global JSON, one file for each ZenPack, containing info for ZenPack and all releases:
	base_jsonfile = "zenpack.json"
	jsonfile = zprepo + "/zenpacks/" + pyname + "/" + base_jsonfile
	log("Writing out JSON to %s..." % jsonfile )
	a = open(jsonfile, 'w')
	json.dump(zenpacks[zp_name], a, sort_keys=True, indent=4, separators=(',',": "))
	a.close()
log("%s builds completed. %s failed. %s skipped (already existed).\n" % (build_count, build_fail, build_exist))
#blog.close()
